### ISSUE TITLE
The getter 'host' isn't defined for the class 'ServiceInfo'

### ISSUE THREAD

**Issue by snaeji** [terrabythia/flutter_chromecast_example#3]
Hi,

I'm trying to run the example and i get the following error:

error: The getter 'host' isn't defined for the class 'ServiceInfo'. (undefined_getter at [flutter_chromecast_example] lib/device_picker.dart:35)

Btw really looking forward to see this package grow!

**Comment by snaeji** [comment]
I think the change there is serviceInfo.address.

I'm still not able to find any devices... does this example still work or has it been broken by some changes?

**Comment by wilsharo** [comment]
@snaeji Give my forked version a try. I made a few updates. 

https://github.com/wilsharo/flutter_chromecast_example

**Comment by snaeji** [comment]
Hey @wilsharo i saw it on another thread and great work! I've made a few changes to the dart_chromecast and flutter_mdns_plugin, it's quite a change with a few customizations and bug fixes, will send a merge request soon!

**Comment by terrabythia** [comment]
Didn't realise but this was already fixed in commit 9c721fae178d06a47ea20f95fd7ebed4a21a535d. See https://github.com/terrabythia/flutter_chromecast_example/commit/9c721fae178d06a47ea20f95fd7ebed4a21a535d#diff-1f0190ebf61d1dc3adc4e252bd86a7cd.
