### ISSUE TITLE
Example crashing in Android Simulator -- UiThread Method called outside of main thread -- in Native code

### ISSUE THREAD

**Issue by burtonmiller** [terrabythia/flutter_chromecast_example#5]
E/AndroidRuntime(12247): FATAL EXCEPTION: NsdManager
E/AndroidRuntime(12247): Process: com.deadsimpletech.mdns2, PID: 12247
E/AndroidRuntime(12247): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: NsdManager
E/AndroidRuntime(12247): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime(12247): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime(12247): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime(12247): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:151)
E/AndroidRuntime(12247): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
E/AndroidRuntime(12247): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime(12247): 	at eu.sndr.fluttermdnsplugin.handlers.DiscoveryRunningHandler.onDiscoveryStarted(DiscoveryRunningHandler.java:22)
E/AndroidRuntime(12247): 	at eu.sndr.fluttermdnsplugin.FlutterMdnsPlugin$1.onDiscoveryStarted(FlutterMdnsPlugin.java:123)
E/AndroidRuntime(12247): 	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:379)
E/AndroidRuntime(12247): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12247): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12247): 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by pharshdev** [comment]
Failing on real device too.

**Comment by pharshdev** [comment]
Crashing on real device too.

**Comment by snaeji** [comment]
This is a issue with the mdns plugin. Check out this pull request:
https://github.com/terrabythia/flutter_mdns_plugin/pull/7

**Comment by terrabythia** [comment]
> This is a issue with the mdns plugin. Check out this pull request:
> [terrabythia/flutter_mdns_plugin#7](https://github.com/terrabythia/flutter_mdns_plugin/pull/7)

This pull request is now merged. Can you please try again?

**Comment by pharshdev** [comment]
Not crashing anymore. Thanks.

**Comment by eemp** [comment]
Should the pubspec.yaml reference to the `service_lost_handler` be updated to `master` instead?

See: https://github.com/terrabythia/flutter_chromecast_example/blob/master/pubspec.yaml#L12

The example works for me as well once I do that.

**Comment by terrabythia** [comment]
@eemp Yes, you're right. Updated the ref in pubspec.yaml.
